-- | Parameter-free support lemmas for algorithmic weakening.
--
--   Everything in here is independent of the canonical-split lemma (agent C1) and
--   only talks about `dom`, `_↓_`, `count`, `𝐂.wk` and the mobility constraints
--   generated by A-Abs.
module BorrowedCF.Completeness.Weaken.Support where

import Relation.Binary.Construct.Closure.Equivalence as Eq*

open import Data.Fin.Subset as S renaming (⊥ to ⁅⁆)
open import Data.Fin.Subset.Properties renaming (∉⊥ to ∉⁅⁆; ⊥⊆ to ⁅⁆⊆)
open import Data.List.Relation.Unary.All as All using (All; []; _∷_)
import Data.List.Relation.Unary.All.Properties as All
open import Relation.Nullary.Decidable using (dec-true; dec-false)

open import BorrowedCF.Prelude
open import BorrowedCF.Types renaming (Solved to SolvedTy)
open import BorrowedCF.Types.Unification
open import BorrowedCF.Context
open import BorrowedCF.Context.Domain
open import BorrowedCF.Algorithmic
open import BorrowedCF.Completeness.Sub.Base using (Approx; subTy-unr⁻¹)
open import BorrowedCF.Algorithmic.Solved

import BorrowedCF.Context.Substitution as 𝐂
open import BorrowedCF.Context.Substitution using (_∶_⇒_; ⇔→⇒; wk-⇔; Kᵣ; weakenᵣ)

open Nat.Variables

private variable
  α β : Struct n
  Z : Subset n
  x y : 𝔽 n

------------------------------------------------------------------------
-- Restriction and domains
------------------------------------------------------------------------

-- Restricting to `X ∩ Z` is restricting to `X` as soon as Z covers the domain.
-- This is what lets us hand the canonical-split lemma a subset that is contained
-- in `dom γ`, so its Unr side conditions become discharge-able.
↓-∩ : ∀ (γ : Struct n) {X Z : Subset n} → dom γ ⊆ Z → γ ↓ (X ∩ Z) ≡ γ ↓ X
↓-∩ (` y) {X} {Z} ⊆Z with y ∈? X
... | yes y∈X rewrite dec-true (y ∈? (X ∩ Z)) (x∈p∩q⁺ (y∈X , ⊆Z (x∈⁅x⁆ y))) = refl
... | no  y∉X rewrite dec-false (y ∈? (X ∩ Z)) (λ y∈ → y∉X (proj₁ (x∈p∩q⁻ X Z y∈))) = refl
↓-∩ [] ⊆Z = refl
↓-∩ (α ∥ β) ⊆Z =
  cong₂ _∥_ (↓-∩ α (⊆-trans (p⊆p∪q _) ⊆Z)) (↓-∩ β (⊆-trans (q⊆p∪q _ _) ⊆Z))
↓-∩ (α ; β) ⊆Z =
  cong₂ _;_ (↓-∩ α (⊆-trans (p⊆p∪q _) ⊆Z)) (↓-∩ β (⊆-trans (q⊆p∪q _ _) ⊆Z))

-- A variable of γ that survives the restriction stays in the domain.
∈-dom-↓ : ∀ (γ : Struct n) {X : Subset n} {x} → x ∈ dom γ → x ∈ X → x ∈ dom (γ ↓ X)
∈-dom-↓ (` y) {X} x∈ x∈X with x∈⁅y⁆⇒x≡y y x∈
... | refl rewrite dec-true (y ∈? X) x∈X = x∈⁅x⁆ y
∈-dom-↓ [] x∈ x∈X = ⊥-elim (∉⁅⁆ x∈)
∈-dom-↓ (α ∥ β) x∈ x∈X =
  x∈p∪q⁺ (Sum.map (λ h → ∈-dom-↓ α h x∈X) (λ h → ∈-dom-↓ β h x∈X) (x∈p∪q⁻ _ _ x∈))
∈-dom-↓ (α ; β) x∈ x∈X =
  x∈p∪q⁺ (Sum.map (λ h → ∈-dom-↓ α h x∈X) (λ h → ∈-dom-↓ β h x∈X) (x∈p∪q⁻ _ _ x∈))

∉-dom-↓ : ∀ (γ : Struct n) {X : Subset n} {x} → x ∈ X → x ∉ dom (γ ↓ X) → x ∉ dom γ
∉-dom-↓ γ x∈X x∉ x∈γ = x∉ (∈-dom-↓ γ x∈γ x∈X)

-- Pointwise reading of AllCx.
allCx-dom : ∀ {ℓ} {P : Pred 𝕋 ℓ} {Γ : Ctx n} {γ : Struct n} {x} →
  AllCx P Γ γ → x ∈ dom γ → P (Γ ﹫ x)
allCx-dom {γ = ` y} (` p) x∈ with x∈⁅y⁆⇒x≡y y x∈
... | refl = p
allCx-dom {γ = []} [] x∈ = ⊥-elim (∉⁅⁆ x∈)
allCx-dom {γ = α ∥ β} (a ∥ b) x∈ = [ allCx-dom a , allCx-dom b ]′ (x∈p∪q⁻ _ _ x∈)
allCx-dom {γ = α ; β} (a ; b) x∈ = [ allCx-dom a , allCx-dom b ]′ (x∈p∪q⁻ _ _ x∈)

-- Every variable that γ₂ has beyond γ₁ is unrestricted.  (Pointwise form of
-- `≼⇒extra-Unr`.)
extra-unr : ∀ {Γ : Ctx n} {γ₁ γ₂ : Struct n} {x} →
  Γ ∶ γ₁ ≼ γ₂ → x ∈ dom γ₂ → x ∉ dom γ₁ → Unr (Γ ﹫ x)
extra-unr {γ₂ = γ₂} w x∈ x∉ = allCx-dom (≼⇒extra-Unr w) (∈-dom-↓ γ₂ x∈ (x∉p⇒x∈∁p x∉))

------------------------------------------------------------------------
-- Moving context facts between the uvar context Γ̂ and the solved context Γ
------------------------------------------------------------------------

-- One pointwise map moves an AllCx between two contexts and two predicates.
allCx-transfer : ∀ {ℓ₁ ℓ₂} {P : Pred 𝕋 ℓ₁} {Q : Pred 𝕋 ℓ₂}
  {Γ₁ Γ₂ : Ctx n} {α : Struct n} →
  (∀ x → P (Γ₁ ﹫ x) → Q (Γ₂ ﹫ x)) → AllCx P Γ₁ α → AllCx Q Γ₂ α
allCx-transfer f []      = []
allCx-transfer f (a ∥ b) = allCx-transfer f a ∥ allCx-transfer f b
allCx-transfer f (a ; b) = allCx-transfer f a ; allCx-transfer f b
allCx-transfer f (`_ {x = x} p) = ` f x p

-- Two contexts that agree up to ≃ prove the same ≈ and ≼ facts (`Unr` and
-- `Mobile` respect ≃, and those are the only places a context is looked at).
CtxEq : Ctx n → Ctx n → Set
CtxEq Γ₁ Γ₂ = ∀ x → Γ₁ ﹫ x ≃ Γ₂ ﹫ x

≈′-ctx-≃ : CtxEq Γ₁ Γ₂ → Γ₁ ∶ α ≈′ β → Γ₂ ∶ α ≈′ β
≈′-ctx-≃ eq ;′-assoc     = ;′-assoc
≈′-ctx-≃ eq (;′-cong₁ d) = ;′-cong₁ (≈′-ctx-≃ eq d)
≈′-ctx-≃ eq (;′-cong₂ d) = ;′-cong₂ (≈′-ctx-≃ eq d)
≈′-ctx-≃ eq ∥′-unit      = ∥′-unit
≈′-ctx-≃ eq ∥′-assoc     = ∥′-assoc
≈′-ctx-≃ eq ∥′-comm      = ∥′-comm
≈′-ctx-≃ eq (∥′-cong₁ d) = ∥′-cong₁ (≈′-ctx-≃ eq d)
≈′-ctx-≃ eq (∥′-dup U)   = ∥′-dup (allCx-transfer (λ x u → unr-≃ (eq x) u) U)
≈′-ctx-≃ eq (∥′-tm-; U)  =
  ∥′-tm-; (Sum.map (allCx-transfer (λ x m → mobile-≃ (eq x) m))
                   (allCx-transfer (λ x m → mobile-≃ (eq x) m)) U)

≈-ctx-≃ : CtxEq Γ₁ Γ₂ → Γ₁ ∶ α ≈ β → Γ₂ ∶ α ≈ β
≈-ctx-≃ eq = Eq*.map (≈′-ctx-≃ eq)

≼-ctx-≃ : CtxEq Γ₁ Γ₂ → Γ₁ ∶ α ≼ β → Γ₂ ∶ α ≼ β
≼-ctx-≃ eq (≼-refl d)      = ≼-refl (≈-ctx-≃ eq d)
≼-ctx-≃ eq (≼-∅ U)         = ≼-∅ (allCx-transfer (λ x u → unr-≃ (eq x) u) U)
≼-ctx-≃ eq ≼-wk            = ≼-wk
≼-ctx-≃ eq (≼-trans d e)   = ≼-trans (≼-ctx-≃ eq d) (≼-ctx-≃ eq e)
≼-ctx-≃ eq (≼-cong-; d e)  = ≼-cong-; (≼-ctx-≃ eq d) (≼-ctx-≃ eq e)
≼-ctx-≃ eq (≼-cong-∥ d e)  = ≼-cong-∥ (≼-ctx-≃ eq d) (≼-ctx-≃ eq e)

-- `Γ̂ approximates Γ` says exactly that `subCtx Γ̂ σ` and `Γ` agree up to ≃.
approx⇒ctxEq : ∀ {n} (σ : UV.Sub) (Γ̂ Γ : Ctx n) → Approx Γ̂ Γ σ → CtxEq (subCtx Γ̂ σ) Γ
approx⇒ctxEq σ Γ̂ Γ ap x =
  subst (_≃ _) (sym (V.lookup-map x (λ t → subTy t σ) Γ̂)) (ap x)

-- `Unr` travels from the uvar context to the solved one (and back, by
-- `unrCx-approx` of Completeness/Sub/Base.agda).
unrCx-fwd : ∀ {n} (σ : UV.Sub) (Γ̂ Γ : Ctx n) {α : Struct n} →
  Approx Γ̂ Γ σ → UnrCx Γ̂ α → UnrCx Γ α
unrCx-fwd σ Γ̂ Γ ap = allCx-transfer (λ x u → unr-≃ (ap x) (subTy-unr u))

------------------------------------------------------------------------
-- Weakening the mobility constraints of A-Abs
------------------------------------------------------------------------

-- `SolvedΔ (allMobile Γ γ) σ` is exactly `AllCx (λ T → Mobile (subTy T σ)) Γ γ`;
-- the two conversions let us reuse `allCx-weaken`.
MobSub : UV.Sub → Pred 𝕋 0ℓ
MobSub σ T = Mobile (subTy T σ)

allMobile⇒AllCx : ∀ (Γ : Ctx n) (γ : Struct n) {σ} →
  SolvedΔ (allMobile Γ γ) σ → AllCx (MobSub σ) Γ γ
allMobile⇒AllCx Γ (` x) (p ∷ _) = ` p
allMobile⇒AllCx Γ [] s = []
allMobile⇒AllCx Γ (α ∥ β) s =
  allMobile⇒AllCx Γ α (All.++⁻ˡ (allMobile Γ α) s) ∥
  allMobile⇒AllCx Γ β (All.++⁻ʳ (allMobile Γ α) s)
allMobile⇒AllCx Γ (α ; β) s =
  allMobile⇒AllCx Γ α (All.++⁻ˡ (allMobile Γ α) s) ;
  allMobile⇒AllCx Γ β (All.++⁻ʳ (allMobile Γ α) s)

AllCx⇒allMobile : ∀ (Γ : Ctx n) (γ : Struct n) {σ} →
  AllCx (MobSub σ) Γ γ → SolvedΔ (allMobile Γ γ) σ
AllCx⇒allMobile Γ (` x) (` p) = p ∷ []
AllCx⇒allMobile Γ [] a = []
AllCx⇒allMobile Γ (α ∥ β) (a ∥ b) =
  All.++⁺ (AllCx⇒allMobile Γ α a) (AllCx⇒allMobile Γ β b)
AllCx⇒allMobile Γ (α ; β) (a ; b) =
  All.++⁺ (AllCx⇒allMobile Γ α a) (AllCx⇒allMobile Γ β b)

-- The constraint-transfer statement for A-Abs.  Note the DIRECTION: the new
-- derivation runs under the LARGER structure γ₂, so it emits the constraints of
-- γ₂; they are solved by σ because γ₁'s are and every extra variable of γ₂ is Unr,
-- hence mobile.  The constraints live over the uvar context Γ̂ while the ≼ lives
-- over the solved context Γ, so the round trip goes through `allCx-transfer`.
mobConstraints-weaken : ∀ {n} (M : Mob) (σ : UV.Sub) (Γ̂ : Ctx n) {Γ : Ctx n}
  {γ₁ γ₂ : Struct n} →
  Approx Γ̂ Γ σ → Γ ∶ γ₁ ≼ γ₂ →
  SolvedΔ (mobConstraints M Γ̂ γ₁) σ →
  SolvedΔ (mobConstraints M Γ̂ γ₂) σ
mobConstraints-weaken S σ Γ̂ ap w s = []
mobConstraints-weaken M σ Γ̂ {Γ} {γ₁} {γ₂} ap w s =
  AllCx⇒allMobile Γ̂ γ₂
    (allCx-transfer (λ x m → mobile-≃ (≃-sym (ap x)) m)
      (allCx-weaken unr⇒mobile w
        (allCx-transfer (λ x m → mobile-≃ (ap x) m)
          (allMobile⇒AllCx Γ̂ γ₁ s))))

------------------------------------------------------------------------
-- Weakening under a binder
------------------------------------------------------------------------

wk-≼ : ∀ {Γ : Ctx n} {T} {α β : Struct n} → Γ ∶ α ≼ β → (T ⸴ Γ) ∶ 𝐂.wk α ≼ 𝐂.wk β
wk-≼ {Γ = Γ} {T = T} w = ≼-⋯ ⦃ Kᵣ ⦄ ϕ⇒ w
  where
    ϕ⇒ : weakenᵣ ∶ Γ ⇒ (T ⸴ Γ)
    ϕ⇒ = ⇔→⇒ ⦃ Kᵣ ⦄ {Γ = Γ} {Γ′ = T ⸴ Γ} (wk-⇔ ⦃ Kᵣ ⦄ {Γ = Γ})

